# -*- coding: utf-8 -*-
"""automate_Satriana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dLWC1Cw-JrIphH_mwpP3PRY1Q7Mu-DFi

# **Otomatisasi proses preprocessing**

Dataset : Student Performance in Exams

**1. Import Library**
"""

# import libabry yang diperlukan

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

# Membuat fungsi utama untuk otomatisasi preprocessing dataset

def preprocess_students_data(input_path, output_path):
  """
  Fungsi ini digunakan untuk melakukan preprocessing data pada dataset student performance.

  Tahapan preprocessing yang dilakukan:
  1. Membaca data dari file CSV.
  2. Menangani missing value.
  3. Menghapus data duplikat
  4. Melakukan normalisasi data menggunakan StandardScaler.
  5. Deteksi dan penanganan outlier
  6. Melakukan encoding pada kolom kategorical.
  7. Binning (pengelompokkan data)
  8. Split dataset menjadi data train dan test.
  9. Simpan hasil preprocessing ke dalam file CSV.

  """

  # 1. Membaca dataset
  print("1. Membaca dataset")
  df = pd.read_csv(input_path)
  print("Jumlah data awal: ", df.shape)

  # 2. Menangani missing value
  print("2. Menangani missing value")
  if df.isnull().values.any():
    print("Terdapat missing value")
    df = df.dropna()
    print("Jumlah data setelah dihapus missing value: ", df.shape)

  # 3 Menghapus data duplikat
  print("3. Menghapus data duplikat")
  df.drop_duplicates(inplace=True)
  print("Jumlah data setelah dihapus duplikat: ", df.shape)

  # 4. Melakukan normalisasi data menggunakan StandardScaler.
  print("4. Melakukan normalisasi data")
  scaler = StandardScaler()
  numerical_cols = ['math score', 'reading score', 'writing score']
  df[numerical_cols] = scaler.fit_transform(df[numerical_cols])
  print("Normalisasi selesai")

  # 5. Deteksi dan penanganan outlier
  print("5. Deteksi dan penanganan outlier")
  z_scores = np.abs((df[numerical_cols] - df[numerical_cols].mean()) / df[numerical_cols].std())
  df = df[(z_scores < 3).all(axis=1)]
  print("Jumlah data setelah dihapus outlier: ", df.shape)

  # 4. Membuat kolom rata-rata (average score)
  print("4. Membuat kolom rata-rata (average score)")
  df['average_score'] = df[['math score', 'reading score', 'writing score']].mean(axis=1)

  # 6. Melakukan encoding pada kolom kategorikal
  print("6. Melakukan encoding pada kolom kategorikal")
  label_cols = ['gender', 'race/ethnicity', 'parental level of education',
                'lunch', 'test preparation course']
  le = LabelEncoder()
  for col in label_cols:
    df[col] = le.fit_transform(df[col])
  print("Encoding selesai")

  # 7. Binning (pengelompokkan data)
  print("7. Binning (pengelompokkan data)")
  bins = [-np.inf, -0.5, 0.5, np.inf]
  labels = ['low', 'medium', 'high']
  df['average_score_binned'] = pd.cut(df['average_score'], bins=bins, labels=labels)
  print("Binning selesai")

  # 8. Split dataset menjadi data train dan test.
  print("8. Split dataset menjadi data train dan test")
  X = df.drop(['average_score'], axis=1)
  y = df['average_score']
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
  print("Split dataset selesai")

  # 9. Simpan hasil preprocessing ke dalam file CSV.
  print("9. Simpan hasil preprocessing ke dalam file CSV")
  df.to_csv(output_path, index=False)
  print(f"Preprocessing tersimpan di : {output_path}")

  return {
      'df': df,
      'X_train': X_train,
      'X_test': X_test,
      'y_train': y_train,
      'y_test': y_test
  }

# Contoh penggunaan fungsi preprocess_students_data
if __name__ == "__main__":
    input_path = 'studentsperformance_raw/StudentsPerformance.csv'  # dataset asli
    output_path = 'preprocessing/studentsperformance_preprocessing/StudentsPerformance_preprocessing.csv' # dataset hasil preprocessing
    results = preprocess_students_data(input_path, output_path)

    print("Data preprocessing selesai.")
    print("Dataframe shape:", results['df'].shape)
    print("Hasil preprocessing tersimpan di:", output_path)
